import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI (if using Firebase)
import 'screens/splash_screen.dart'; // Make sure this file exists

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase if you're using it
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // MaterialApp with the home set to our SplashScreen
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Prescription App',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.blue),
      // The initial screen is the splash screen
      home: const SplashScreen(),
      routes: {
        // Define your routes here (for example, login, home, etc.)
        // '/login': (context) => const LoginScreen(),
      },
    );
  }
}
